{% set name = "pgrouting" %}
{% set version = "2.6.1" %}
{% set sha256 = "c45211a7f9db9fa58a1593b65a23eb892e39ade3e6777e0bdd1e63c1b49241d3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pgrouting/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: 
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make install
  skip: True  # [win]


requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cgal
    - cmake
    - perl
    - pkg-config
    - postgresql
    - postgis
  run:
    - {{ pin_compatible('cgal', exact=True) }}
    - postgis
    - postgresql

test:
  commands:
    # These are not needed, tests are run in run_test.sh
    - true

about:
  home: http://github.com/pgrouting/pgrouting
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'pgRouting extends PostGIS/PostgreSQL geospatial database to provide geospatial routing and other network analysis functionality.'

  doc_url: https://docs.pgrouting.org
  dev_url: https://github.com/pgrouting/pgrouting

extra:
  recipe-maintainers:
    - sodre
